### PR TITLE
Docker setup finished.

### PR DESCRIPTION
**Pull request by Wuljo318**

### CODE REVIEW

**Review by marijaboss — APPROVED** [review]
Everything is OK.

**Review by nrisek — APPROVED** [review]
Good as always.

**Review by StjepanCecura — APPROVED** [review]
Docker is set up properly

**Review by mfric20 — CHANGES_REQUESTED** [review]
Change the name of the service to "receipts" to match given documentation

**Review by mfric20 — APPROVED** [review]

**Pull request merged**
